Update wubbaR

diff --git a/wubbaR b/wubbaR
--- a/wubbaR
+++ b/wubbaR
@@ -53,10 +53,12 @@ osInfo=""
 osRelease=""
 osReleaseVersion=""
 osReleaseVersionNo=""
+osReleaseVersionNoShort=""
 osReleaseVersionCodeName="CodeName"
 osSystemPackage=""
 osSystemMdPath=""
 osSystemShell="bash"
+
 
 pwd=`pwd`
 wpt=22335
@@ -84,6 +86,8 @@ FIND_STR2="xnd"
 str_RCLOCAL="sh /etc/init.d/xnd start &"
 
 
+#centos
+FIND_CRCSERVER="/lib/systemd/system/nginx.service"
 
 Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
 Info="${Green_font_prefix}[信息]${Font_color_suffix}"
@@ -219,7 +223,10 @@ getLinuxOSVersion(){
         osInfo=$(uname -s)
         osReleaseVersionNo=$(uname -r)
     fi
+
+    osReleaseVersionNoShort=$(echo $osReleaseVersionNo | sed 's/\..*//')
 }
+
 
 
 
@@ -342,74 +349,13 @@ function setLinuxDateZone(){
 }
 
 
-function cro_nginx_user(){
-echo    "创建Nginx运行用户"
-groupadd www
-useradd -g www www -s /sbin/nologin
-}
-
-function Install_nginx(){
-	if [[ -e ${nginxConfigPath} ]]; then
-		green " nginx 已安装 , 是否覆盖安装(更新)？[y/N]"
-		read -e -p "(默认: n):" yn
-		[[ -z ${yn} ]] && yn="n"
-		if [[ ${yn} == [Nn] ]]; then
-			echo "已取消..." && exit 1
-		fi
-	else
-		green " nginx 未安装，开始安装..."
-	fi
-
-    cro_nginx_user
-    
-    if [[ "$osRelease" == "ubuntu" ]] || [[ "$osRelease" == "debian" ]]; then
-    osSysudo apt install build-essential -y
-    fi
-    
-    # 下载nginx文件
-    if ! wget --no-check-certificate -O ${pwd}/nginx-1.21.3.tar.gz https://nginx.org/download/nginx-1.21.3.tar.gz; then
-        echo "下载nginx文件失败！"
-
-            if ! wget --no-check-certificate -O ${pwd}/nginx-1.21.3.tar.gz http://nginx.org/download/nginx-1.21.3.tar.gz; then
-        echo "下载nginx文件失败！"
-        exit 1
-    fi
-        exit 1
-    fi
-
-		green " 解压..."
-		tar -xzf ${pwd}/nginx-1.21.3.tar.gz && cd ${pwd}/nginx-1.21.3
-		green " 编译安装..."
-		./configure --prefix=$nghm --user=www --group=www --with-http_ssl_module --with-http_flv_module --with-http_stub_status_module --with-http_gzip_static_module --with-pcre --with-stream --with-poll_module
-        make -j$Nolp
-        make install
-        
-
-
-	[[ ! -e ${BIN} ]] && red " nginx 安装失败 !" && exit 1
-
-
-	echo && green " nginx 安装成功 !" && echo
-}
-
-
-
-
-
-
-
-
 
 function service_nginx_centos(){
 	cat > /etc/init.d/xnd<<-EOF
-#!/bin/bash
-# chkconfig: 2345 90 10
-# description: nginx
-
 ### BEGIN INIT INFO
 # Provides:          nginx
-# Required-Start:    \$network \$syslog
-# Required-Stop:     \$network
+# Required-Start:    \$network \$local_fs \$remote_fs
+# Required-Stop:     \$network \$local_fs \$remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Lightweight SOCKS5 proxy tool
@@ -421,8 +367,9 @@ NAME_BIN="nginx"
 FOLDER="$nghm"
 BIN="$nghm/sbin/nginx"
 
+
 check_running(){
-	PID=`PID=\`ps -ef |grep -v grep | grep nginx |awk '{print \$2}'\`
+	PID=\`ps -ef |grep -v grep | grep nginx |awk '{print \$2}'\`
 	if [[ ! -z \${PID} ]]; then
 		return 0
 	else
@@ -432,10 +379,12 @@ check_running(){
 do_start(){
 	check_running
 	if [[ \$? -eq 0 ]]; then
-		echo -e "\${Info_font_prefix}[信息]\${Font_suffix} \$NAME (PID ${PID}) 正在运行..." && exit 0
+	echo -e "\${Info_font_prefix}[信息]\${Font_suffix} \$NAME (PID \${PID}) 正在运行..." && exit 0
 	else
 		cd \${FOLDER}
-		nohup "\$BIN"  &
+		#python_ver=\$(ls /usr/bin|grep -e "^python[23]\.[1-9]\+\$"|tail -1)
+
+		nohup  "\$BIN" &
 		sleep 2s
 		check_running
 		if [[ \$? -eq 0 ]]; then
@@ -453,12 +402,12 @@ do_stop(){
 		if [[ \$RETVAL -eq 0 ]]; then
 			echo -e "\${Info_font_prefix}[信息]\${Font_suffix} \$NAME 停止成功 !"
 		else
-			echo -e "\${Error_font_prefix}[错误]\${Font_suffix} \$NAME 停止失败 !"
-                        echo -e "\${Error_font_prefix}[错误]\${Font_suffix} \$NAME killall !"
-                        killall nginx
+			echo -e "\${Error_font_prefix}[错误]\${Font_suffix}\$NAME 停止失败 !"
+            killall nginx
+			echo -e "\${Info_font_prefix}[信息]\${Font_suffix} \$NAME 强行停止 !"
 		fi
 	else
-		echo -e "\${Info_font_prefix}[信息]\${Font_suffix} \$NAME 未运行"
+		echo -e "\${Info_font_prefix}[信息]\${Font_suffix} \$NAME 未运行 !"
 		RETVAL=1
 	fi
 }
@@ -471,25 +420,26 @@ do_status(){
 		RETVAL=1
 	fi
 }
+
+do_reload() {
+    \$BIN -s reload
+}
+
 do_restart(){
 	do_stop
 	do_start
-}
-do_reload(){
-        \$BIN -s reload
 }
 case "\$1" in
 	start|stop|restart|status|reload)
 	do_\$1
 	;;
 	*)
-	echo -e "使用方法: \$0 { start | stop | restart | status reload }"
+	echo "使用方法: \$0 { start | stop | restart | status | reload }"
 	RETVAL=1
 	;;
 esac
 exit \$RETVAL
 EOF
-
 }
 
 
@@ -508,7 +458,7 @@ function service_nginx_debian(){
 
 NAME="nginx"
 NAME_BIN="nginx"
-FOLDER="$nghm/"
+FOLDER="$nghm"
 BIN="$nghm/sbin/nginx"
 
 
@@ -647,7 +597,8 @@ restart() {
 # 防火墙设置firewall_set_drop  firewall_set
 function firewall_set_ACCEPT(){
     echo "防火墙设置启动..."
-    if [ `echo ${osReleaseVersionNo} | awk -v tem="6" '{print($1>tem)? "1":"0"}'` -eq "0" ];then
+    #if [ `echo ${osReleaseVersionNo} | awk -v tem="6" '{print($1>tem)? "1":"0"}'` -eq "0" ];then
+     if  [[ ${osReleaseVersionNoShort} == "6" ]]; then
         systemctl status firewalld > /dev/null 2>&1
         /etc/init.d/iptables status > /dev/null 2>&1
         if [ $? -eq 0 ]; then
@@ -685,7 +636,7 @@ function firewall_set_ACCEPT(){
         else
             echo "警告：iptables可能已关闭或未安装，如有必要，请手动设置."
         fi
-    elif [ `echo ${osReleaseVersionNo} | awk -v tem="7" '{print($1>tem)? "1":"0"}'` -eq "0" ];then
+    elif  [[ ${osReleaseVersionNoShort} == "7" ]]; then
         systemctl status firewalld > /dev/null 2>&1
         systemctl status firewalld > /dev/null 2>&1
         if [ $? -eq 0 ];then
@@ -702,7 +653,7 @@ function firewall_set_ACCEPT(){
             done
                 firewall-cmd --reload
         fi
-    elif [ `echo ${osReleaseVersionNo} | awk -v tem="8" '{print($1>tem)? "1":"0"}'` -eq "0" ];then
+    elif  [[ ${osReleaseVersionNoShort} == "8" ]]; then
         systemctl status firewalld > /dev/null 2>&1
         systemctl status firewalld > /dev/null 2>&1
         if [ $? -eq 0 ];then
@@ -746,7 +697,7 @@ function firewall_set_ACCEPT(){
 # 防火墙设置关闭
 function firewall_set_drop(){
     echo "防火墙设置启动..."
-    if [ `echo ${osReleaseVersionNo} | awk -v tem="6" '{print($1>tem)? "1":"0"}'` -eq "0" ];then
+    if  [[ ${osReleaseVersionNoShort} == "6" ]]; then
         /etc/init.d/iptables status > /dev/null 2>&1
         if [ $? -eq 0 ]; then
             uname-a
@@ -781,7 +732,7 @@ function firewall_set_drop(){
         else
             echo "警告：iptables可能已关闭或未安装，如有必要，请手动设置."
         fi
-    elif [ `echo ${osReleaseVersionNo} | awk -v tem="7" '{print($1>tem)? "1":"0"}'` -eq "0" ];then
+    elif  [[ ${osReleaseVersionNoShort} == "7" ]]; then
         systemctl status firewalld > /dev/null 2>&1
         if [ $? -eq 0 ];then
             wp_array=($(awk '{print}' $FOLDER/wub/config.txt))
@@ -797,7 +748,7 @@ function firewall_set_drop(){
             done
                 firewall-cmd --reload
         fi        
-    elif [ `echo ${osReleaseVersionNo} | awk -v tem="8" '{print($1>tem)? "1":"0"}'` -eq "0" ];then
+    elif  [[ ${osReleaseVersionNoShort} == "8" ]]; then
         systemctl status firewalld > /dev/null 2>&1
         systemctl status firewalld > /dev/null 2>&1
         if [ $? -eq 0 ];then
@@ -1035,6 +986,7 @@ function removeNginx(){
          rm -rf $ssnginx
          ls | grep -P "nginx" | xargs -d"\n" rm -rf
          rm -rf $nghm/wub/isok
+         rm -rf /etc/init.d/xnd
         green " ================================================== "
         green "[ wubbaPool 卸载成功! ]"
     else
@@ -1206,32 +1158,94 @@ function install_wubba(){
 
 #服务
 function Service_nginx(){
-	if [[ ${release} = "centos" ]]; then
-    #centos8自启
-    echo"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx服务centos"
-    if [ $osReleaseVersionNo -eq 8 ]; then
-    echo"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx服务centos8"
-    cat > /etc/rc.d/rc.local<<-EOF
-$nghm/sbin/nginx
-EOF
-    else
-    echo "开机自启设置失败！"
-fi
-		#if ! wget --no-check-certificate https://cdn.staticaly.com/gh/lihuate/MinerReverseProxy/mainnginx_centos -O /etc/init.d/xnd; then
+#centos服务
+        		#if ! wget --no-check-certificate https://cdn.staticaly.com/gh/lihuate/MinerReverseProxy/mainnginx_centos -O /etc/init.d/xnd; then
 		#	red " nginx服务 管理脚本下载失败 !" && exit 1
 		#fi
-        service_nginx_centos
-		chmod +x /etc/init.d/xnd
-		chkconfig --add xnd
-		chkconfig xnd on
+  if [ "$osRelease" == "centos" ]; then
+              green " =================================================="
+                    service_nginx_centos
+		            chmod +x /etc/init.d/xnd
+            red " 生成 Centos 配置文件"
+            green " =================================================="
 
- fi
+        if  [[ ${osReleaseVersionNoShort} == "5" ]]; then
+            green " =================================================="
+            red " 本脚本不支持 Centos 5 或 Centos 5 更早的版本"
+            green " =================================================="
+            exit
+        fi
+        if  [[ ${osReleaseVersionNoShort} == "6" ]]; then
+            green " =================================================="
+		           chkconfig --add xnd
+		           chkconfig xnd on
+            red " 设置 Centos 6 开机自启"
+            green " =================================================="
+            exit
+        fi
 
-if [ "$osRelease" == "ubuntu" ]; then
-    echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx服务Ubuntu"
+        if  [[ ${osReleaseVersionNoShort} == "7" ]]; then
+            green " =================================================="
+echo "
+[Unit]    
+Description=nginx    
+After=network.target         
+[Service]    
+Type=forking    
+User=nginx
+Group=nginx
+ExecStart=/etc/init.d/xnd start    
+ExecReload=/etc/init.d/xnd restart    
+ExecStop=/etc/init.d/xnd  stop    
+PrivateTmp=true    
+[Install]    
+WantedBy=multi-user.target">$FIND_CRCSERVER
+
+echo "设置开机自启动"  
+chmod +x /usr/lib/systemd/system/nginx.service
+systemctl enable nginx.service
+
+            red " 设置 Centos 7 开机自启"
+            green " =================================================="
+            exit
+        fi      
+        if  [[ ${osReleaseVersionNoShort} == "8" ]]; then
+            green " =================================================="
+echo "
+[Unit]    
+Description=nginx    
+After=network.target         
+[Service]    
+Type=forking    
+User=nginx
+Group=nginx
+ExecStart=/etc/init.d/xnd start    
+ExecReload=/etc/init.d/xnd restart    
+ExecStop=/etc/init.d/xnd  stop    
+PrivateTmp=true    
+[Install]    
+WantedBy=multi-user.target">$FIND_CRCSERVER
+
+echo "设置开机自启动"  
+chmod +x /usr/lib/systemd/system/nginx.service
+systemctl enable nginx.service
+
+        fi
+            red " 设置 Centos 8 开机自启"
+            green " =================================================="
+            exit
+        fi        
+
 		#if ! wget --no-check-certificate https://cdn.staticaly.com/gh/lihuate/MinerReverseProxy/mainnginx_debian -O /etc/init.d/xnd; then
 			#red " nginx服务 管理脚本下载失败 !" && exit 1
 		#fi
+        if [ "$osRelease" == "ubuntu" ] || [ "$osRelease" == "debian" ] ; then
+        if  [[ ${osReleaseVersionNoShort} == "12" ]]; then
+            green " =================================================="
+            red " 本脚本不支持 Ubuntu 12 或 Ubuntu 12 更早的版本"
+            green " =================================================="
+            exit
+        fi
         service_nginx_debian
 		chmod +x /etc/init.d/xnd
 		update-rc.d -f xnd defaults
@@ -1239,80 +1253,148 @@ if [ "$osRelease" == "ubuntu" ]; then
 # -f 参数判断 $file 是否存在
 echo "xxxx参数判断 FIND_RCSERVER 是否存在"
 if [ ! -f "$FIND_RCSERVER" ]; then
+echo "不存在>>创建"
   touch $FIND_RCSERVER 
 fi
 # 判断匹配函数，匹配函数不为0，则包含给定字符
 echo "xxxx判断[Install]"
 if [ `grep -c "$FIND_STR" $FIND_RCSERVER` -ne '0' ];then
-    echo "The File Has  [Install]!"S
+    echo "The File Has  [Install]!"
     else
+    echo "不存在>>写入启动信息[$FIND_STR]"
 echo "
 [Install]
 WantedBy=multi-user.target
-Alias=rc-local.service">>$FIND_RCSERVER
+Alias=rc-local.service">>$FIND_RCSERVER 
 fi
-${osSystemPackage} chmod 777 $FIND_RCSERVER
-
 
 # -f 参数判断 $file 是否存在
 echo "参数判断$FIND_RCLOCAL 是否存在"
 if [ ! -f "$FIND_RCLOCAL" ]; then
+    echo "不存在>>创建写入信息[$FIND_RCLOCAL]"
   touch $FIND_RCLOCAL
   echo "#!/bin/bash">>$FIND_RCLOCAL
 fi
-${osSystemPackage} chmod +x $FIND_RCLOCAL
+
 # 判断匹配函数，匹配函数不为0，则包含给定字符
 echo "参数判断$FIND_STR2 是否存在"
 if [ `grep -c "$FIND_STR2" $FIND_RCLOCAL` -ne '0' ];then
     echo "The File Has  [init.d]!"
     else
+    echo "不存在>>写入启动信息[$str_RCLOCA]"    
 echo "$str_RCLOCAL">>$FIND_RCLOCAL
 fi
-ln -s /lib/systemd/system/rc.local.service /etc/systemd/system/
+
+
+# -f 参数判断 $file 是否存在
+echo "参数判断/usr/lib/systemd/system/rc-local.service.d/debian.conf 是否存在"
+if [ -f "/usr/lib/systemd/system/rc-local.service.d/debian.conf" ]; then
+    echo "不存在>>写入启动信息"
+echo "
+[Install]
+WantedBy=multi-user.target
+Alias=rc-local.service">>/usr/lib/systemd/system/rc-local.service.d/debian.conf
 fi
-	green " nginx 管理脚本完成 !"
+
+${osSystemPackage} chmod 777 /lib/systemd/system/rc.local.service &>/dev/null
+${osSystemPackage} chmod 777 /etc/rc.local &>/dev/null
+ln -s /lib/systemd/system/rc.local.service /etc/systemd/system/ &>/dev/null
+chmod +x /etc/rc.local &>/dev/null
+systemctl enable rc-local &>/dev/null
+systemctl start rc-local.service &>/dev/null
+fi
 }
 
 
 # 软件安装
-
 function installSoftDownload(){
     echo
-    green " =================================================="
+    green " ================================================================"
     yellow " 开始安装软件"
-    green " =================================================="
+    green " ================================================================"
     echo
- echo "=================installSoftDownload==================================================="
+ echo "=================installSoftDownload============================================================================================================================="
+
+
+    if [ "$osRelease" == "centos" ]; then
+	    echo "a==============$osRelease" == "centos=更新系统============================================================================================================a"
+        ${osSystemPackage} update  -y
+        echo "a==============$osRelease" == "centos=make===============================================================================================================a"
+        ${osSystemPackage} install -y make
+        echo "a==============$osRelease" == "centos=make===============================================================================================================a"
+        ${osSystemPackage} install -y gcc g++
+        echo "a==============$osRelease" == "centos=make===============================================================================================================a"
+        ${osSystemPackage} install -y automake autoconf libtool
+        ${osSystemPackage} install -y curl curl-devel
+        ${osSystemPackage} install -y openssl openssl-devel
+        ${osSystemPackage} install -y zlib zlib-devel
+        ${osSystemPackage} install -y pcre pcre-devel
+        echo "a==============$osRelease" == "centos=软件包安装结束=======================================================================================================a"
+        fi
+
+
+
+
 	if [[ "$osRelease" == "ubuntu" ]] || [[ "$osRelease" == "debian" ]]; then  
-    echo "===================================================================="
+             echo "a==============$osRelease" == "ubuntu===============================================================================================================a"
             ${osSystemPackage} update -y
-    echo "=================ubuntu======debian============================================="
-			${osSystemPackage} -y install wget git unzip build-essential
-				echo "a=============================================================================================================================a"
-            ${osSystemPackage} install -y wget
-	            echo "a========================sssssssssssss=====================================================================================================a"
-	        ${osSystemPackage} install -y build-essential
-	            echo "a========================ssssssssssssss=====================================================================================================a"
+            echo "a========================ssssssssssssss==============================================================================================================a"
+			${osSystemPackage} -y install wget git unzip 
+			echo "a========================ssssssssssssss==============================================================================================================a"
+            ${osSystemPackage} install -y make build-essential
+	        echo "a========================ssssssssssssss==============================================================================================================a"
             ${osSystemPackage} install -y curl
             ${osSystemPackage} install -y curl-devel
-	        echo "a=============================================================================================================================a"
+	        echo "a========================ssssssssssssss==============================================================================================================a"
             ${osSystemPackage} install -y libpcre3 libpcre3-dev
-	        echo "a=============================================================================================================================a"
+	        echo "a========================ssssssssssssss==============================================================================================================a"
             ${osSystemPackage} install -y zlib1g zlib1g-dev
             ${osSystemPackage} install -y openssl libssl-dev
 			# https://stackoverflow.com/questions/11116704/check-if-vt-x-is-activated-without-having-to-reboot-in-linux
 		fi
-
-
-    if [ "$osRelease" == "centos" ]; then
-
-        ${osSystemPackage} update  -y
-        ${osSystemPackage} install -y gcc curl curl-devel
-        ${osSystemPackage} install -y openssl openssl-devel
-        ${osSystemPackage} install -y zlib zlib-devel pcre pcre-devel
-        fi
 }
 
+function cro_nginx_user(){
+echo    "创建Nginx运行用户"
+groupadd www
+useradd -g www www -s /sbin/nologin
+}
+
+function Install_nginx(){
+	if [[ -e ${nginxConfigPath} ]]; then
+		green " nginx 已安装 , 是否覆盖安装(更新)？[y/N]"
+		read -e -p "(默认: n):" yn
+		[[ -z ${yn} ]] && yn="n"
+		if [[ ${yn} == [Nn] ]]; then
+			echo "已取消..." && exit 1
+		fi
+	else
+		green " nginx 未安装，开始安装..."
+	fi
+
+    cro_nginx_user
+    
+    # 下载nginx文件
+    if ! wget --no-check-certificate -O ${pwd}/nginx-1.21.3.tar.gz https://nginx.org/download/nginx-1.21.3.tar.gz; then
+        echo "下载nginx文件失败！"
+
+            if ! wget --no-check-certificate -O ${pwd}/nginx-1.21.3.tar.gz http://nginx.org/download/nginx-1.21.3.tar.gz; then
+        echo "下载nginx文件失败！"
+        exit 1
+    fi
+        exit 1
+    fi
+
+		green " 解压..."
+		tar -xzf ${pwd}/nginx-1.21.3.tar.gz && cd ${pwd}/nginx-1.21.3
+		green " 编译安装..."
+		./configure --prefix=$nghm --user=www --group=www --with-http_ssl_module --with-http_flv_module --with-http_stub_status_module --with-http_gzip_static_module --with-pcre --with-stream --with-poll_module
+        make -j$Nolp
+        make install 
+
+	[[ ! -e ${BIN} ]] && red " nginx 安装失败 !" && exit 1
+	echo && green " nginx 安装成功 !" && echo
+}
 
 
 # 显示 菜单状态
